const SELECT_ARTIST = "artists.SELECT_ARTIST";
const SET_ARTISTS = "artists.SET_ARTISTS";
const UPDATE_ARTIST_SEARCH_TERM = "artists.UPDATE_ARTIST_SEARCH_TERM";

export { SELECT_ARTIST, SET_ARTISTS, UPDATE_ARTIST_SEARCH_TERM };
