const SET_CURRENT_SETLIST_ID = "setlists.SET_CURRENT_SETLIST_ID";
const SET_PLAYLIST_ID = "setlists.SET_PLAYLIST_ID";
const SET_SETLISTS = "setlists.SET_SETLISTS";

export { SET_CURRENT_SETLIST_ID, SET_PLAYLIST_ID, SET_SETLISTS };
